#!/usr/bin/env bash
if [[ "$OSTYPE" == "linux-gnu" ]]; then
	notify-send --icon=info "$(xsel -o)" "$(wget -U "Mozilla/5.0" -qO - "https://api.dictionaryapi.dev/api/v1/entries/en/$(xsel -o | sed "s/[\"'<>]//g")" --inet4-only | sed "s/,,,0]],,.*//g" | grep "definition" | tr -d '"')"
fi
if [[ "$OSTYPE" == "darwin"* ]]; then
	terminal-notifier -title "$(pbpaste)" -message "$(wget -U "Mozilla/5.0" -qO - "https://api.dictionaryapi.dev/api/v1/entries/en/$(pbpaste | sed "s/[\"'<>]//g")" | sed "s/,,,0]],,.*//g" | grep "definition" | tr -d '"' )"
fi
