#!/usr/bin/env bash
notify-send --icon=info "$(xsel -o)" "$(wget -U "Mozilla/5.0" -qO - "https://googledictionaryapi.eu-gb.mybluemix.net/?define=$(xsel -o | sed "s/[\"'<>]//g")&lang=en" | sed "s/,,,0]],,.*//g" | grep "definition")"

# https://googledictionaryapi.eu-gb.mybluemix.net/?define=gerrymandering&lang=en
